# -*- coding: utf-8 -*-
"""Copy of Solomon_ABCDs_Detector.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JHUKMBueeAr2VDOF3Kjf2deV8AgiKLYw

```
Copyright 2024 Google LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
```

# ABCDs Detector

The ABCDs Detector solution offers a streamlined solution for understanding how video ads align with key metrics within the [YouTube ABCD Framework](https://www.thinkwithgoogle.com/intl/en-emea/future-of-marketing/creativity/youtube-video-ad-best-practices/). Powered by Google AI, the tool leverages a data-driven analysis to automate the ABCD assessment, providing an objective and comprehensive report of adherence across a collection of defined features. By combining **Video** And **LLM** Google AI models, ABCDs Detector automates the evaluation process and delivers comprehensive reports on how well your ads align with the ABCD framework. This empowers you to optimize your YouTube ad campaigns for maximum impact.

## Evaluation Methods

ABCDs Detector performs 2 types of verifications depending on the feature, evaluation using **annotations** or using **LLMs**. The evaluation method is determined based on research and performance for each feature, but it's configurable and can be changed in the features repository.
Since the LLM approach is prone to hallucinations, False Positives or False Negatives will be expected. The solution will still require human QA if 100% accuracy is required for the evaluation.

## Gemini Pro (LLM)

LLMs are used to assess features against YouTube's ABCD framework rubrics. This enables the detector to "ask questions" and determine if the ad adheres to each rubric.  See [Vertex AI](https://cloud.google.com/vertex-ai) documentation.

## Video Intelligence API (Video)

Google AI extracts features and identifies key moments within your video ads. See [Google Video Intelligence API](https://cloud.google.com/video-intelligence?hl=en) documentation.

### Features Used
  - Label annotations
  - Face annotations
  - Text annotations
  - Object annotations
  - People annotations
  - Speech annotations
  - Shot annotations
  - Logo annotations

## Features

ABCDs Detector supports a single video evaluation for the following features/rubrics: **Long Form ABCD** and **Shorts**.

Please check the latest list of features in the ABCD Detector [repository](https://github.com/google-marketing-solutions/abcds-detector)  

## Cost
With the Multimodal models in Vertex AI, you can input either text or media (images, video). Text input is charged by every 1,000 characters of input (prompt) and every 1,000 characters of output (response). Characters are counted by UTF-8 code points and white space is excluded from the count. Prediction requests that lead to filtered responses are charged for the input only. At the end of each billing cycle, fractions of one cent ($0.01) are rounded to one cent. Media input is charged per image or per second (video). For more details please check the official documentation: https://cloud.google.com/vertex-ai/generative-ai/pricing

### Cost
Prices are per minute. Partial minutes are rounded up to the next full minute. Volume is per month. For more details please check the official [documentation](https://cloud.google.com/video-intelligence/pricing).

# Requirements
Please esure you have access to all of the following before starting:
* [Google Cloud Project](https://cloud.google.com) with enabled APIs:
    * [Video Intelligence API](https://console.cloud.google.com/marketplace/product/google/videointelligence.googleapis.com)
    * [Vertex AI API](https://console.cloud.google.com/marketplace/product/google/aiplatform.googleapis.com)
    * [Knowledge Graph API](https://console.cloud.google.com/marketplace/product/google/kgsearch.googleapis.com)
    * [Cloud Storage API](https://console.cloud.google.com/marketplace/product/google/storage.googleapis.com)
* [API Key](https://cloud.google.com/docs/authentication/api-keys) provisioned.
* [Project Billing](https://cloud.google.google.com/billing/) enabled.
* Python libraries:
    * `google-cloud-videointelligence`
    * `google-cloud-aiplatform`

# Instructions
Please follow the steps below before executing the ABCDs Detector solution. Every **[VARIABLE]** is a parameter you can configure in the **Define ABCDs Detector Parameters** section.

1. Store your videos on [Google Cloud Storage](https://console.cloud.google.com/storage/browser).
   * **[BUCKET_NAME]** - the place where this tool will store annotation data under **ABCD** folder. Clear this to redo annotations.
   * **[VIDEO_URIS]** - a list of video URIs that will be processed, can be any path but should match brand information if EXTRACT_BRAND_METADATA is False.
      * The URI will be evaluated as is for any creative provider.
      * For GCS creative provider, if the URI is a folder path that ends with **/**, then it will be expanded, all the files in that path will be evaluated.

1. Make sure the requirements are met:
   * Enable APIs:
      * [Video Intelligence API](https://console.cloud.google.com/marketplace/product/google/videointelligence.googleapis.com)
      * [Vertex AI API](https://console.cloud.google.com/marketplace/product/google/aiplatform.googleapis.com)
      * [Knowledge Graph API](https://console.cloud.google.com/marketplace/product/google/kgsearch.googleapis.com)
      * [Cloud Storage API](https://console.cloud.google.com/marketplace/product/google/storage.googleapis.com)
   * Provision [An API Key](https://cloud.google.com/docs/authentication/api-keys):
      1. Visit [Credentials Page](https://cloud.console.google.com/apis/credentials).
      1. Create a **New API Key** and copy it into **[KNOWLEDGE_GRAPH_API_KEY]** below.
      1. We recommend editing and restricting the key to the above APIs.

1. Define all the parameters.
   * Required:
      * Google Cloud Project Details
      * ABCD Detector Configuration
      * Brand And Product Configuration
   * Optional
      * Annotations Configuration
      * LLM Configuration

1. Run all of the steps in sequence.
   * Some steps do not produce output, they only define functions.
   * If a step asks you to **Restart Runtime**, do so.
   * If a step displays an error, stop and debug it. Debug the following:
      * APIs are enabled.
      * Storage bucket is correctly configured.
      * The video is the correct size.
      * API Key has correct restrictions.
      * Previous code sections completed.
      * Select _Runtime > Reset Session and Run All_ as a last resort.
   * The **Run ABCDs Detector** step produces the video analysis.

1. For questions, please reach out to: abcds-detector@google.com

# Install ABCD Detector Code
"""

# Commented out IPython magic to ensure Python compatibility.
!git clone -b shorts_features_added https://github.com/wing-lol/abcds-detector > /dev/null 2>&1 # 2>&1 — redirects stderr (standard error, error messages) to stdout
!python3 -m pip install -q google-cloud-aiplatform==1.97.0 # -q: quiet
!python3 -m pip install -q google-cloud-videointelligence==2.16.1
!python3 -m pip install -q google-cloud-storage==2.19.0
!python3 -m pip install -q moviepy==1.0.3
!python3 -m pip install -q google-api-python-client==2.172.0
!python3 -m pip install -q pandas==2.2.2
!python3 -m pip install -q pyarrow==19.0.1
# %cd /content/abcds-detector

print("✅ Setup complete!")

"""# Define ABCDs Detector Parameters"""

#!/usr/bin/env python3

###########################################################################
#
#  Copyright 2024 Google LLC
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#
###########################################################################

from configuration import Configuration
config = Configuration()
from google.colab import userdata

# @markdown ### Google Cloud Project Configuration

PROJECT_ID = "branderator-smart-demo"  # @param {type:"string", placeholder:"Google Cloud Project ID"}
PROJECT_ZONE = "us-central1"# @param {type:"string", placeholder:"Google Cloud Project Zone"}
BUCKET_NAME = "solomon_abcd_ds"  # @param {type:"string", placeholder:"Google Cloud Sotrage Bucket for annotations"}
KNOWLEDGE_GRAPH_API_KEY_NAME = 'abcd_key' # @param {type:"string", placeholder:"abcd_key"}
BQ_DATASET_NAME = "abcd_detector_ds" # @param {type:"string"}
BQ_TABLE_NAME = "abcd_assessments_solomon" # @param {type:"string"}
ASSESSMENT_FILE = ""  # @param {type:"string", placeholder:"optional local file to write assesments to"}

# @markdown ### ABCD Detector Configuration

USE_ANNOTATIONS = False  # @param {type:"boolean"}
USE_LLMS = True  # @param {type:"boolean"}

RUN_LONG_FORM_ABCD = False  # @param {type:"boolean"}
RUN_SHORTS = True  # @param {type:"boolean"}

EXTRACT_BRAND_METADATA = False  # @param {type:"boolean"}
# @markdown ###### [ EXTRACT_BRAND_METADATA - If True, it will extract the brand metadata to evaluate each video individually. If False, it will use the brand and product details defined below to evaluate ALL the videos. ]
CREATIVE_PROVIDER_TYPE = "GCS"  # @param {type:"string"}
# @markdown ###### [ CREATIVE_PROVIDER_TYPE - The location where the creatives are located. Supported creative providers: GCS and YOUTUBE ]
VERBOSE = True  # @param {type:"boolean"}

config.set_parameters(
      project_id=PROJECT_ID,
      project_zone=PROJECT_ZONE,
      bucket_name=BUCKET_NAME,
      knowledge_graph_api_key=userdata.get(KNOWLEDGE_GRAPH_API_KEY_NAME),
      bigquery_dataset=BQ_DATASET_NAME,
      bigquery_table=BQ_TABLE_NAME,
      assessment_file=ASSESSMENT_FILE,
      extract_brand_metadata=EXTRACT_BRAND_METADATA,
      use_annotations=USE_ANNOTATIONS,
      use_llms=USE_LLMS,
      run_long_form_abcd=RUN_LONG_FORM_ABCD,
      run_shorts=RUN_SHORTS,
      features_to_evaluate=[], # TODO (ae) add this later
      creative_provider_type=CREATIVE_PROVIDER_TYPE,
      verbose=VERBOSE,
  )

# @markdown ### Brand and Product Configuration

BRAND_NAME = "Salomon"  # @param {type:"string"}
# @markdown ###### [ BRAND_NAME - Required ]
BRAND_VARIATIONS = "Salomon, Salomon Group, S/LAB, Salomon Sportstyle"  # @param {type:"string"}
BRANDED_PRODUCTS = "XT-6, Speedcross 6, XA Pro 3D V9, X Ultra 5 Gore-Tex, Quest 5 Gore-Tex, ACS Pro, S/Lab Phantasm 3, S/Lab Genesis, Aero Glide 4, Sense Ride 5, Pulsar 4, Thundercross, S/Pro Alpha 130, QST Echo 106, Adv Skin 12, Active Skin 8"  # @param {type:"string"}
BRANDED_PRODUCT_CATEGORIES = "Trail Running, Road Running, Gravel Running, Hiking & Backpacking, Sportstyle & Sneakers, Alpine Skiing, Snowboarding, Nordic & Cross-Country Skiing, Forces (Tactical), Apparel & Clothing, Bags & Packs, Accessories & Equipment"  # @param {type:"string"}
BRANDED_CALL_TO_ACTIONS = "Tomorrow is Yours, Shaping New Futures, Welcome Back to Earth, Time to Play, Invented in the Mountains. Reinvented in the City., Unleash the best version of yourself, Born in the French Alps"  # @param {type:"string"}

config.set_brand_details(
    brand_name = BRAND_NAME,
    brand_variations = BRAND_VARIATIONS,
    products = BRANDED_PRODUCTS,
    products_categories = BRANDED_PRODUCT_CATEGORIES,
    call_to_actions = BRANDED_CALL_TO_ACTIONS
)

# @markdown ### Annotations Configuration

EARLY_TIME_SECONDS = 5
CONFIDENCE_THRESHOLD = 0.5  # @param {type:"number"}
FACE_SURFACE_THRESHOLD = 0.15  # @param {type:"number"}
LOGO_SIZE_THRESHOLD = 3.5  # @param {type:"number"}
AVG_SHOT_DURATION_SECONDS = 2  # @param {type:"number"}
DYNAMIC_CUTOFF_MS = 3000  # @param {type:"number"}

config.set_annotations_params(
    early_time_seconds = EARLY_TIME_SECONDS,
    confidence_threshold = CONFIDENCE_THRESHOLD,
    face_surface_threshold =  FACE_SURFACE_THRESHOLD,
    logo_size_threshold = LOGO_SIZE_THRESHOLD,
    avg_shot_duration_seconds = AVG_SHOT_DURATION_SECONDS,
    dynamic_cutoff_ms = DYNAMIC_CUTOFF_MS
)

# @markdown ### LLM Configuration

LLM_NAME = "gemini-2.5-pro"  # @param {type:"string"}
LOCATION = "us-central1" # @param {type:"string"}
MAX_OUTPUT_TOKENS = 65535  # @param {type:"number"}
TEMPERATURE = 0  # @param {type:"number"}
TOP_P = 0.95  # @param {type:"number"}

config.set_llm_params(
    llm_name=LLM_NAME,
    location=LOCATION,
    max_output_tokens=MAX_OUTPUT_TOKENS,
    temperature=TEMPERATURE,
    top_p=TOP_P,
)

"""# Get Video URIs

A new Creative Provider architecture, built on a factory pattern, allows developers to easily integrate and pull creatives from various data sources.
- Supported Providers:
  - Google Cloud Storage Creative Provider: Retrieve individual videos or folders of videos from a GCS bucket.
  - YouTube Creative Provider: Designed to retrieve a list of YouTube URLs. This can be adapted to integrate with the YouTube API for automated retrieval.


### Google Cloud Storage Creative Provider:

You can analyze any video in any project you have access to. The following list takes two possible inputs:

   1. A Google [Cloud Storage URI](https://console.cloud.google.com/storage/) by clicking the **:** icon on the right of a video and selecting **Copy gsutil URI**. The path must be a video file.
   2. A folder path to load all videos in a folder, just remove the video part so the path ends in a forward slash like **gs://????/**.

#### Example Code with GCS uris

```
config.set_videos([
  "gs://cloud-samples-data/generative-ai/video/pixel8.mp4",
])
```

#### Example Code with vith GCS folder

```
config.set_videos([
  "gs://cloud-samples-data/generative-ai/video/"  
])
```

### YouTube Creative Provider:

You can analyze any public YouTube video or any video from a YouTube channel you own.

#### Example Code

```
config.set_videos([
  "https://www.youtube.com/watch?v=x65VVs-aSUI",
  "https://www.youtube.com/watch?v=OMVpP-Zam1A"  
])
```

Please fill the videos in the next section...
"""

# Example with GCS Creative Provider - 9s
config.set_videos([
'gs://solomon_abcd_ds/videos/p8cvwBx4FFk.mp4'
])

"""# Authenticate ABCDs Detector"""

from google.colab import auth
auth.authenticate_user(project_id=config.project_id)

"""# Run ABCDs Detector"""

# Cell: Test your feature
import sys
sys.path.insert(0, '/content/abcds-detector')

from features_repository.shorts.a_shorts_features import get_attract_features
from evaluation_services.video_evaluation_service import VideoEvaluationService
from models import VideoFeatureCategory
from configuration import Configuration
import json

# Get your heartbeat feature
features = get_attract_features()
a_heartbeat = next(f for f in features if f.id == "a_heartbeat_story_arc")

# Evaluate
evaluation_service = VideoEvaluationService()
result = evaluation_service.evaluate_features(
    config=config,
    features_category=VideoFeatureCategory.SHORTS
)

print("Evaluation complete!")
print(result)

from main import execute_abcd_assessment_for_videos
execute_abcd_assessment_for_videos(config)

print("Script execution finished!")

from main import execute_abcd_assessment_for_videos
execute_abcd_assessment_for_videos(config)

print("Script execution finished!")

from main import execute_abcd_assessment_for_videos
execute_abcd_assessment_for_videos(config)

print("Script execution finished!")